#@TYPE: Machine
#@NAME: stm32mp2-efi
#@DESCRIPTION: Configuration example for all STM32MP2 boards (EV, DK, ...) with EFI support
#@NEEDED_BSPLAYERS: layers/meta-openembedded/meta-oe layers/meta-openembedded/meta-python

include stm32mp2.conf

# =========================================================================
# boot device
# =========================================================================
# Define the boot device supported
BOOTDEVICE_LABELS = "emmc"
BOOTDEVICE_LABELS += "sdcard"

# =========================================================================
# EFI
# =========================================================================
# activate EFI feature
MACHINE_FEATURES += "efi"
# force to use a specific tsv prefix name
FLASHLAYOUT_BASENAME = "FlashLayout-EFI"

# Override default config to use 'vfat' fstype for bootfs partition
PARTITIONS_CONFIG[emmc] = "\
    ${@' '.join(['%s' % partImage2partConfig(d, config, 'vfat' if config == 'bootfs' else '${PARTITIONS_SUFFIX}') for config in d.getVar('PARTITIONS_IMAGES').split()])} \
    "
PARTITIONS_CONFIG[sdcard] = "\
    ${@' '.join(['%s' % partImage2partConfig(d, config, 'vfat' if config == 'bootfs' else '${PARTITIONS_SUFFIX}') for config in d.getVar('PARTITIONS_IMAGES').split()])} \
    "

